### ISSUE TITLE
About the function of this init of microVM

### ISSUE THREAD

**Issue by blossomin** [NVIDIA/nvrc#1]
Hello, I wonder the function of this init.

As I can see it, if I use this init for my Kata initrd init process, after this executes, it will call the /sbin/init(which is the original init process). This nvidia init can set up confidential mode GPU for CVM(like mount, setup the CDI). Will this do the remote attestation for the GPU? 

And if I use kata-agent as the /sbin/init, is it still compatible to launch this CVM correctly?

Thanks!

**Comment by zvonkok** [comment]
I prepares all things related to the GPU and hands of the container life-cycle management to the kata-agent.
